#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")

function c () {
	curl "http://localhost:7474/db/data/transaction/commit" \
		--silent \
		--request POST \
		--user "neo4j:admin" \
		--header 'Accept: application/json; charset=UTF-8' \
		--header 'Content-Type: application/json' \
		--header 'X-Stream: true' \
		"$@" | python -m json.tool
}

mkdir --parents "$HERE/data/"

puccini-tosca compile "$HERE/../tosca/requirements-and-capabilities.yaml" | \
puccini-clout scriptlet exec "$HERE/neo4j.js" \
	> "$HERE/data/tosca.json"

c --data '{"statements": [{"statement": "MATCH (n) DETACH DELETE n"}]}'
c --data-binary @"$HERE/data/tosca.json"
c --data '{"statements": [{"statement": "MATCH (n) RETURN n"}]}'
