#!/bin/bash
set -e

# Requirements (Fedora)
# sudo dnf install python3-virtualenv python3-libselinux

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../../scripts/_env"

# virtualenv
# (must use "--system-site-packages" so that Ansible can access localhost on SELinux!)
python3 -m venv --system-site-packages "$ROOT/dist/python-env"
. "$ROOT/dist/python-env/bin/activate"
pip install --upgrade pip

pip install \
	ansible==3.0.0 \
	os-client-config==2.1.0 \
	rackspaceauth==0.8.1
