
ERR_1 = "Error: Not enough info to translate response time."
ERR_2 = "Error: Node type must be NetworkApplication."
ERR_3 = "Error: Application parsing is impossible."
ERR_4 = "Error: Not enough info to translate reliability."
ERR_5 = "Error: Not enough info to translate hardware requirements."
ERR_6 = "Error: Please indicate maximum response time."
ERR_7 = "Error: Please indicate maximum compute time."
ERR_8 = "Error: Latency cannot be larger than response time."
ERR_9 = "Error: Compute time cannot be larger than response time."
ERR_10 = "Error: Sum of latency and compute time cannot be larger than response time."
ERR_11 = "Error: Not enough info to translate number of requests per second."
ERR_12 = "Error: Not enough info to translate number of concurrent users."
ERR_13 = "Error: Not enough info to translate compute time."
ERR_14 = "Error: Node type must be HostNode."
ERR_15 = "Error: Host parsing is impossible."

WARN_1 = "Warning: Certain application properties are not defined. This could impact the result."
WARN_2 = "Warning: Certain application requirements are not defined. This could impact the result."
WARN_3 = "Warning: As per your configuration, latency is negligible against bandwidth."
WARN_4 = "Warning: As per your configuration, bandwidth is negligible against latency."
WARN_5 = "Warning: Certain host properties are not defined. This could impact the result."
WARN_6 = "Warning: Certain host capabilities are not defined. This could impact the result."

NEGLIGIBLE = 0
